# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'dominika-azure'
    subscriptionId: 'e4365b76-5a80-42a1-8bbe-5ce2c37cbe25'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Dominika-AzureRmPipeline-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/DominikaStarostka/AzureRmPipeline-repoz/main/CreateWebApp2/main2.json'
    overrideParameters: '-projectName intern-training-dominika'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
